"""
MintPy configuration template generator.

Generates a smallbaselineApp.cfg (or mintpy_config.txt) file that is
ready to use with: smallbaselineApp.py mintpy_config.txt

The template layout mirrors a known-good hybrid ISCE2/topsStack +
Dolphin + SNAPHU configuration. In particular it emits the lookup
table paths (``lookupYFile`` / ``lookupXFile``) so MintPy can
geocode its radar-geometry results downstream; omitting these is one
of the most common sources of a ``No lookup table found`` failure.
"""

import logging
from pathlib import Path

logger = logging.getLogger(__name__)

MINTPY_CONFIG_TEMPLATE = """\
##------ openeo2mintpy auto-generated configuration for MintPy ------##
## Generated by openeo2mintpy v{version}
## Run with: smallbaselineApp.py {config_name}

mintpy.project.name        = {project_name}

########## Load Data ##########
## Hybrid ISCE2/topsStack + openEO + SNAPHU pipeline:
## metadata is read from the .rsc sidecars produced by openeo2mintpy,
## so metaFile / baselineDir can stay on 'auto'.
mintpy.load.processor      = {processor}
mintpy.load.autoPath       = no
mintpy.load.metaFile       = {meta_file}
mintpy.load.baselineDir    = {baseline_dir}

## Interferograms (Dolphin + SNAPHU outputs)
mintpy.load.unwFile        = {unw_pattern}
mintpy.load.corFile        = {cor_pattern}
mintpy.load.connCompFile   = {conncomp_pattern}

## Geometry (ISCE2 topsStack outputs, radar geometry)
mintpy.load.demFile        = {dem_file}
mintpy.load.incAngleFile   = {inc_angle_file}
mintpy.load.azAngleFile    = {az_angle_file}

## Lookup tables: required to map radar coordinates -> geographic
## references during geocoding. Point these at ISCE2 lat/lon files
## (lat.rdr.full / lon.rdr.full) when the stack is in radar geometry.
mintpy.load.lookupYFile    = {lookup_y_file}
mintpy.load.lookupXFile    = {lookup_x_file}

## Water mask (optional)
mintpy.load.waterMaskFile  = {water_mask_file}

########## Reference Point ##########
mintpy.reference.yx        = {reference_yx}
mintpy.reference.lalo      = {reference_lalo}

########## Network Inversion ##########
mintpy.networkInversion.weightFunc   = {weight_func}
mintpy.networkInversion.maskDataset  = {mask_dataset}
mintpy.networkInversion.minTempCoh   = {min_temp_coh}

########## Tropospheric Delay Correction ##########
## Options: no / pyaps / height_correlation / gacos
mintpy.troposphericDelay.method = no

########## Topographic Residual (DEM Error) ##########
mintpy.topographicResidual = {topo_residual}

########## Velocity Estimation ##########
mintpy.deramp              = no

########## Output ##########
mintpy.save.hdfEos5        = no
mintpy.save.kmz            = yes
"""


def generate_mintpy_config(
    work_dir,
    unw_dir,
    cor_dir=None,
    conncomp_dir=None,
    dem_file=None,
    inc_angle_file=None,
    az_angle_file=None,
    lookup_y_file=None,
    lookup_x_file=None,
    water_mask_file=None,
    processor="isce",
    project_name="openEO2Mintpy_project",
    meta_file="auto",
    baseline_dir="auto",
    reference_yx="auto",
    reference_lalo="auto",
    weight_func="coherence",
    mask_dataset="connectComponent",
    min_temp_coh=0.4,
    config_name="mintpy_config.txt",
    custom_options=None,
):
    """Generate a MintPy-compatible configuration file.

    Creates a smallbaselineApp.cfg-style file with all load_data paths
    pre-configured to point at openEO outputs with .rsc sidecars.

    Parameters
    ----------
    work_dir : str or Path
        MintPy working directory (where config file will be written).
    unw_dir : str or Path
        Directory containing unwrapped phase GeoTIFFs.
    cor_dir : str or Path, optional
        Directory containing coherence GeoTIFFs. Defaults to unw_dir.
    conncomp_dir : str or Path, optional
        Directory containing connected component files. Defaults to unw_dir.
    dem_file : str or Path, optional
        Path (or glob) to the DEM file — e.g. ISCE2 ``hgt.rdr.full``.
    inc_angle_file : str or Path, optional
        Path to the incidence angle file — e.g. ISCE2 ``los.rdr.full``.
    az_angle_file : str or Path, optional
        Path to the azimuth angle file — e.g. ISCE2 ``los.rdr.full``.
    lookup_y_file : str or Path, optional
        Path to the latitude lookup table (ISCE2 ``lat.rdr.full``).
        Required so MintPy can geocode radar-geometry results.
    lookup_x_file : str or Path, optional
        Path to the longitude lookup table (ISCE2 ``lon.rdr.full``).
        Required so MintPy can geocode radar-geometry results.
    water_mask_file : str or Path, optional
        Path (or glob) to a water mask raster.
    processor : str
        ``mintpy.load.processor`` value (``isce`` or ``hyp3``).
        Use ``isce`` when geometry files are ISCE2 ``*.rdr.full`` outputs.
    project_name : str
        Human-readable project label written to the config header.
    meta_file, baseline_dir : str
        Values for ``mintpy.load.metaFile`` and ``mintpy.load.baselineDir``.
        Leave on ``auto`` when .rsc sidecars are supplying the metadata.
    reference_yx, reference_lalo : str
        Values for ``mintpy.reference.yx`` and ``mintpy.reference.lalo``.
    weight_func : str
        ``mintpy.networkInversion.weightFunc`` (e.g. ``coherence`` / ``no``).
    mask_dataset : str
        ``mintpy.networkInversion.maskDataset``.
    min_temp_coh : float
        ``mintpy.networkInversion.minTempCoh``.
    config_name : str
        Output filename for the configuration.
    custom_options : dict, optional
        Additional MintPy options to append (key=value pairs).

    Returns
    -------
    Path
        Absolute path to the generated config file.
    """
    from openeo2mintpy import __version__

    work_dir = Path(work_dir)
    work_dir.mkdir(parents=True, exist_ok=True)

    unw_dir = Path(unw_dir)
    cor_dir = Path(cor_dir) if cor_dir else unw_dir
    conncomp_dir = Path(conncomp_dir) if conncomp_dir else unw_dir

    unw_pattern = _build_pattern(unw_dir, "*.unw.tif")
    cor_pattern = _build_pattern(cor_dir, "*.cor.tif", fallback="*.int.cor.tif")
    conncomp_pattern = _build_pattern(
        conncomp_dir, "*.unw.conncomp.tif", fallback="*.conncomp.tif"
    )

    dem_value = _format_path(dem_file)
    inc_value = _format_path(inc_angle_file)
    az_value = _format_path(az_angle_file)
    lookup_y_value = _format_path(lookup_y_file)
    lookup_x_value = _format_path(lookup_x_file)
    water_value = _format_path(water_mask_file)

    topo_residual = "yes" if dem_file else "no"

    content = MINTPY_CONFIG_TEMPLATE.format(
        version=__version__,
        config_name=config_name,
        project_name=project_name,
        processor=processor,
        meta_file=meta_file or "auto",
        baseline_dir=baseline_dir or "auto",
        unw_pattern=unw_pattern,
        cor_pattern=cor_pattern,
        conncomp_pattern=conncomp_pattern,
        dem_file=dem_value,
        inc_angle_file=inc_value,
        az_angle_file=az_value,
        lookup_y_file=lookup_y_value,
        lookup_x_file=lookup_x_value,
        water_mask_file=water_value,
        reference_yx=reference_yx or "auto",
        reference_lalo=reference_lalo or "auto",
        weight_func=weight_func,
        mask_dataset=mask_dataset,
        min_temp_coh=min_temp_coh,
        topo_residual=topo_residual,
    )

    if custom_options:
        content += "\n########## Custom Options ##########\n"
        for key, value in custom_options.items():
            content += f"{key:<35s} = {value}\n"

    config_path = work_dir / config_name
    with open(config_path, "w") as f:
        f.write(content)

    logger.info("Generated MintPy config: %s", config_path)
    return config_path


def _format_path(value):
    """Render a path-like value for the MintPy config, defaulting to 'auto'."""
    if value is None or value == "":
        return "auto"
    return str(value)


def _build_pattern(directory, primary_pattern, fallback=None):
    """Build a glob pattern string for MintPy load configuration.

    Checks if files matching the primary pattern exist; if not,
    tries the fallback pattern.

    Parameters
    ----------
    directory : Path
        Directory containing the files.
    primary_pattern : str
        Primary glob pattern to try.
    fallback : str, optional
        Fallback glob pattern if primary yields no matches.

    Returns
    -------
    str
        Full glob pattern string (directory/pattern).
    """
    full_pattern = str(directory / primary_pattern)

    if fallback:
        import glob as g
        if not g.glob(full_pattern):
            alt_pattern = str(directory / fallback)
            if g.glob(alt_pattern):
                return alt_pattern

    return full_pattern
